{% set name = "curated-tokenizers" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/curated-tokenizers-{{ version }}.tar.gz
  sha256: c93d47e54ab3528a6db2796eeb4bdce5d44e8226c671e42c2f23522ab1d0ce25

build:
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  missing_dso_whitelist:  # [s390x]
    - $RPATH/ld64.so.1    # [s390x]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cython >=0.25
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - regex >=2022

test:
  imports:
    - curated_tokenizers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/explosion/curated-tokenizers
  dev_url: https://github.com/explosion/curated-tokenizers
  doc_url: https://github.com/explosion/curated-tokenizers
  summary: Lightweight piece tokenization library
  description: spaCy entry points for Curated Transformers.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - skupr-anaconda
